const router = require('express').Router();
const c = require('../controllers/admin.controller');
const { requireAuth, requireRole } = require('../middleware/auth');
router.use(requireAuth, requireRole('admin'));
router.get('/dashboard', c.dashboard);
router.get('/students', c.students);
router.get('/students/:id/profile', c.studentProfile);
router.post('/scanner/student', c.scanStudent);
router.post('/attendance', c.markAttendance);
router.get('/attendance', c.listAttendance);
router.get('/settings', c.settings);
router.post('/study-months', c.saveStudyMonth);
router.delete('/study-months/:faculty/:month', c.deleteStudyMonth);
router.post('/groups', c.saveGroup);
router.delete('/groups/:faculty/:group', c.deleteGroup);
router.post('/faculty/:faculty/lecture-grade', c.saveLectureGrade);
router.post('/faculty/:faculty/approve', c.approve);
router.get('/permissions', c.permissions);
router.put('/permissions/:id', c.savePermissions);
module.exports = router;
