let session = getUser();
let currentPage = 'dashboard';
let scanner = null;
let currentProfile = null;
let activeEvaluation = null;
const monthNames = ['يناير','فبراير','مارس','أبريل','مايو','يونيو','يوليو','أغسطس','سبتمبر','أكتوبر','نوفمبر','ديسمبر'];

const $ = (id) => document.getElementById(id);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg) { const t=$('toast'); t.textContent=msg; t.className='show'; clearTimeout(window._toast); window._toast=setTimeout(()=>t.className='',3000); }
function hideAuth() { ['landing','studentAuth','adminAuth'].forEach(id=>$(id).classList.add('hidden')); }
function goLanding() { stopScanner(); session=null; clearAuth(); hideAuth(); $('app').classList.add('hidden'); $('landing').classList.remove('hidden'); }
function openStudentAuth(){ hideAuth(); $('studentAuth').classList.remove('hidden'); studentAuthTab('login'); }
function openAdminAuth(){ hideAuth(); $('adminAuth').classList.remove('hidden'); $('adminUser').focus(); }
function studentAuthTab(tab){ ['studentLoginForm','studentRegisterForm'].forEach(id=>$(id).classList.add('hidden')); document.querySelectorAll('#studentAuth .auth-tab').forEach(x=>x.classList.remove('active')); if(tab==='login'){ $('studentLoginForm').classList.remove('hidden'); $('studentLoginTab').classList.add('active'); } else { $('studentRegisterForm').classList.remove('hidden'); $('studentRegisterTab').classList.add('active'); loadGroupsForRegister(); } }
function logout(){ stopScanner(); clearAuth(); session=null; $('app').classList.add('hidden'); $('landing').classList.remove('hidden'); }
function openApp(){ hideAuth(); $('app').classList.remove('hidden'); $('studentNav').classList.toggle('hidden',session.role!=='student'); $('adminNav').classList.toggle('hidden',session.role!=='admin'); $('facultyWrap').classList.toggle('hidden',session.role!=='admin'); $('permissionsNav').classList.toggle('hidden',session.role!=='admin'||!session.isMaster); $('currentUser').textContent=session.email?`${session.name} — ${session.email}`:session.name; session.role==='admin'?adminPage('dashboard'):studentPage('dashboard'); }
function init(){
  $('studentLoginForm').onsubmit=e=>{e.preventDefault(); studentLogin();}; $('studentRegisterForm').onsubmit=e=>{e.preventDefault(); registerStudent();}; $('adminLoginForm').onsubmit=e=>{e.preventDefault(); adminLogin();};
  if(session) openApp();
}
async function studentLogin(){ try{const r=await api('/auth/student/login',{method:'POST',body:JSON.stringify({nationalId:$('loginNational').value.trim(),password:$('loginPassword').value})}); setAuth(r.token,r.user); session=r.user; openApp();}catch(e){toast(e.message);} }
async function adminLogin(){ try{const r=await api('/auth/admin/login',{method:'POST',body:JSON.stringify({email:$('adminUser').value.trim(),password:$('adminPass').value})}); setAuth(r.token,r.user); session=r.user; openApp();}catch(e){toast(e.message);} }
async function demoStudentLogin(){ try{const r=await api('/auth/student/login',{method:'POST',body:JSON.stringify({nationalId:'29901010101010',password:'123456'})}); setAuth(r.token,r.user); session=r.user; openApp();}catch(e){toast(e.message);} }
async function resetStudent(){ const nationalId=prompt('أدخل الرقم القومي'); if(!nationalId)return; try{const r=await api('/auth/student/reset',{method:'POST',body:JSON.stringify({nationalId:nationalId.trim()})}); toast(r.message||'تمت العملية');}catch(e){toast(e.message);} }
async function loadGroupsForRegister(){ $('regGroup').innerHTML='<option value="">اختر المجموعة</option>'+Array.from({length:30},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join(''); $('regGroup').onchange=async()=>{ try{const r=await api(`/student/group-preview/${$('regGroup').value}`); const g=r.group; if(!g){$('groupPreview').classList.add('hidden');return;} $('groupPreview').classList.remove('hidden'); $('groupPreview').innerHTML=`📍 ${esc(g.location)}<br>👨‍🏫 ${esc(g.facultyMember)}<br>👥 ${esc(g.assistant)}<br>🧑‍💼 ${esc(g.external)}`;}catch{ $('groupPreview').classList.add('hidden'); } };
}
async function registerStudent(){ const b={name:$('regName').value.trim(),nationalId:$('regNational').value.trim(),phone:$('regPhone').value.trim(),seatNumber:$('regSeat').value.trim(),group:Number($('regGroup').value),password:$('regPassword').value}; if(b.password!==$('regPassword2').value)return toast('تأكيد كلمة المرور غير مطابق'); try{const r=await api('/auth/student/register',{method:'POST',body:JSON.stringify(b)}); setAuth(r.token,r.user); session=r.user; openApp();}catch(e){toast(e.message);} }
function setTitle(title){$('pageTitle').textContent=title; document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active')); const key=currentPage; document.querySelectorAll('.nav').forEach(x=>{ if((x.getAttribute('onclick')||'').includes(`'${key}'`))x.classList.add('active'); }); }
function adminPage(p){ stopScanner(); currentPage=p; setTitle({dashboard:'الرئيسية',students:'الطلاب',scanner:'فحص QR',attendance:'الحضور',evaluation:'التقييم',study:'شهور الدراسة',data:'البيانات',review:'مراجعة واعتماد',export:'تصدير',settings:'الإعدادات',permissions:'الصلاحيات'}[p]||'الرئيسية'); renderAdmin(); }
function reloadAdminPage(){ adminPage(currentPage); }
function studentPage(p){ currentPage=p; setTitle(p==='dashboard'?'بيانات الطالب':'الحضور والتقييم'); renderStudent(); }
function card(title,body,cls=''){return `<div class="card ${cls}"><h3>${title}</h3>${body}</div>`;}
async function renderStudent(){ try{const r=await api('/student/me'); const s=r.student; const a=r.attendance; const sum=r.summary; $('content').innerHTML=`<div class="grid"><div class="card stat"><div class="label">إجمالي المحاضرات</div><div class="value">${a.totalLectures}</div></div><div class="card stat"><div class="label">إجمالي الحضور</div><div class="value">${a.present}</div></div><div class="card stat"><div class="label">نسبة الحضور</div><div class="value">${a.percentage.toFixed(1)}%</div></div><div class="card stat"><div class="label">المجموع الكلي</div><div class="value">${sum.total}</div></div></div><div class="grid2" style="margin-top:16px"><div class="card"><h3>بيانات الطالب</h3>${profileHtml(s)}</div><div class="card qr-box"><div id="studentQr"></div><div class="qr-number">${esc(s.code)}</div><small class="muted">QR خاص بالطالب — الكود ${esc(s.code)}</small></div></div>${card('بيانات الإشراف',`<div class="grid2"><p>عضو هيئة التدريس: <b>${esc(s.facultyMember)}</b></p><p>عضو الهيئة المعاونة: <b>${esc(s.assistant)}</b></p><p>المشرف الخارجي: <b>${esc(s.external)}</b></p><p>مكان التدريب: <b>${esc(s.training)}</b></p></div>`)}${attendanceTable(r)}${evaluationTable(sum.evaluations)} `; if(window.QRCode)new QRCode($('studentQr'),{text:s.qrToken,width:190,height:190}); }catch(e){ if(e.status===401)logout(); else toast(e.message); } }
function profileHtml(s){return `<p>الاسم: <b>${esc(s.name)}</b></p><p>الكود: <b>${esc(s.code)}</b></p><p>الرقم القومي: <b>${esc(s.nationalId||'-')}</b></p><p>الهاتف: <b>${esc(s.phone||'-')}</b></p><p>رقم الجلوس: <b>${esc(s.seatNumber||'-')}</b></p><p>الفرقة: <b>${s.faculty}</b></p><p>المجموعة: <b>${s.group||'-'}</b></p>`;}
function attendanceTable(r){return card('الحضور',`<div class="table-wrap"><table class="table"><thead><tr><th>الشهر</th><th>المحاضرات</th><th>الحضور</th><th>الغياب</th><th>النسبة</th><th>التقييم</th></tr></thead><tbody>${r.monthly.map(x=>`<tr><td>${esc(x.month)}</td><td>${x.lectures}</td><td>${x.present}</td><td>${x.absent}</td><td>${x.percentage.toFixed(1)}%</td><td>${x.evaluationScore==null?'-':`${x.evaluationScore}/${x.evaluationMax}`}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد بيانات</td></tr>'}</tbody></table></div>`);}
function evaluationTable(rows){return card('درجات التقييم',`<div class="table-wrap"><table class="table"><thead><tr><th>الشهر</th><th>الدرجة</th><th>النهائي</th><th>التاريخ</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.month)}</td><td>${x.score}</td><td>${x.max}</td><td>${esc(x.date)}</td></tr>`).join('')||'<tr><td colspan="4" class="empty">لا توجد تقييمات</td></tr>'}</tbody></table></div>`);}
async function renderAdmin(){ const f=$('adminFaculty').value; try{
  if(currentPage==='dashboard'){const r=await api(`/admin/dashboard?faculty=${f}`); $('content').innerHTML=`<div class="grid"><div class="card stat"><div class="label">طلاب الفرقة ${f}</div><div class="value">${r.students}</div></div><div class="card stat"><div class="label">الحسابات المنشأة</div><div class="value">${r.accounts}</div></div><div class="card stat"><div class="label">حضور اليوم</div><div class="value">${r.attendanceToday}</div></div><div class="card stat"><div class="label">التقييمات</div><div class="value">${r.evaluations}</div></div></div>${card('لوحة الإدارة',`<p>استخدم <b>فحص QR</b> لقراءة بطاقة الطالب واستدعاء بياناته الكاملة.</p><p>الحساب الإداري يرى فقط الطلاب في مجموعاته المصرح بها، بينما Master يرى الجميع.</p>`)}`; return;}
  if(currentPage==='students')return renderStudents(f);
  if(currentPage==='scanner')return renderScanner();
  if(currentPage==='attendance')return renderAttendance(f);
  if(currentPage==='evaluation')return renderEvaluation(f);
  if(currentPage==='study')return renderStudy(f);
  if(currentPage==='data')return renderData(f);
  if(currentPage==='review')return renderReview(f);
  if(currentPage==='export')return renderExport();
  if(currentPage==='settings')return renderSettings();
  if(currentPage==='permissions')return renderPermissions();
 }catch(e){if(e.status===401)logout();else toast(e.message);}}
async function renderStudents(f){const r=await api(`/admin/students?faculty=${f}`); $('content').innerHTML=card('الطلاب',`<div class="actions"><input id="studentSearch" class="search" placeholder="بحث بالاسم أو الرقم القومي أو رقم الجلوس أو الكود"><button class="ghost" onclick="filterStudents()">بحث</button></div><div id="studentList" class="table-wrap" style="margin-top:15px">${studentsTable(r.students)}</div>`);}
function studentsTable(students){return `<table class="table"><thead><tr><th>الاسم</th><th>الكود</th><th>الجلوس</th><th>المجموعة</th><th>الحالة</th><th></th></tr></thead><tbody>${students.map(s=>`<tr><td>${esc(s.name)}</td><td>${esc(s.code)}</td><td>${esc(s.seatNumber)}</td><td>${s.group||'-'}</td><td>${s.registered?'نشط':'لم ينشئ حسابًا'}</td><td><button class="mini" onclick="openStudentProfile('${s._id}')">عرض</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">لا توجد بيانات</td></tr>'}</tbody></table>`;}
async function filterStudents(){const f=$('adminFaculty').value,q=$('studentSearch').value.trim();try{const r=await api(`/admin/students?faculty=${f}&search=${encodeURIComponent(q)}`);$('studentList').innerHTML=studentsTable(r.students);}catch(e){toast(e.message);}}
async function openStudentProfile(id){try{const r=await api(`/admin/students/${id}/profile`);showScannedProfile(r,false);}catch(e){toast(e.message);}}
function renderScanner(){ $('content').innerHTML=`<div class="grid2"><div class="card"><h3>📷 فحص QR الطالب</h3><p class="muted">اسمح للمتصفح بالوصول إلى الكاميرا. بعد الفحص سيظهر ملف الطالب كاملًا إذا كان ضمن صلاحيات حسابك.</p><div id="scannerReader" class="scanner">الكاميرا جاهزة للتشغيل</div><div class="actions"><button class="primary" onclick="startStudentScanner()">تشغيل الكاميرا</button><button class="ghost" onclick="stopScanner()">إيقاف</button></div></div><div id="scanResult" class="card result-area"><h3>نتيجة الفحص</h3><p class="muted">لم يتم فحص QR بعد.</p></div></div>`; }
async function startStudentScanner(){if(!window.Html5Qrcode)return toast('مكتبة QR غير متاحة');stopScanner(); scanner=new Html5Qrcode('scannerReader'); try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},async txt=>{stopScanner(); try{const r=await api('/admin/scanner/student',{method:'POST',body:JSON.stringify({qrToken:String(txt).trim()})}); currentProfile=r;showScannedProfile(r,true);}catch(e){toast(e.message);}});}catch(e){toast('تعذر تشغيل الكاميرا. استخدم HTTPS أو localhost ومنح صلاحية الكاميرا.');}}
function stopScanner(){if(scanner){try{scanner.stop().catch(()=>{});}catch{} scanner.clear?.(); scanner=null;}}
function showScannedProfile(r,scanned){currentProfile=r; const s=r.student,a=r.attendance,sum=r.summary; $('scanResult')?.replaceChildren(); const target=$('scanResult')||$('content'); const html=`<div class="student-profile-head"><div><h3>${esc(s.name)}</h3><p class="muted">الكود ${esc(s.code)} — المجموعة ${s.group||'-'} — الفرقة ${s.faculty}</p></div><span class="badge ok">تم التعرف</span></div><div class="profile-grid">${profileHtml(s)}<p>مكان التدريب: <b>${esc(s.training||'-')}</b></p><p>عضو هيئة التدريس: <b>${esc(s.facultyMember||'-')}</b></p><p>الهيئة المعاونة: <b>${esc(s.assistant||'-')}</b></p><p>المشرف الخارجي: <b>${esc(s.external||'-')}</b></p></div><div class="grid" style="margin-top:12px"><div class="card soft"><div class="label">المحاضرات</div><div class="value smallv">${a.totalLectures}</div></div><div class="card soft"><div class="label">الحضور</div><div class="value smallv">${a.present}</div></div><div class="card soft"><div class="label">الغياب</div><div class="value smallv">${a.absent}</div></div><div class="card soft"><div class="label">نسبة الحضور</div><div class="value smallv">${a.percentage.toFixed(1)}%</div></div></div>${evaluationTable(sum.evaluations)}<div class="total-strip"><span>إجمالي التقييمات: <b>${sum.evaluationTotal}/${sum.evaluationMax}</b></span><span>المجموع الكلي: <b>${sum.total}</b></span></div><div class="actions"><button class="primary" onclick="markScannedAttendance()">✅ تسجيل حضور اليوم</button></div>`; if(target.id==='scanResult')target.innerHTML=`<h3>نتيجة الفحص</h3>${html}`; else target.innerHTML=html; }
async function markScannedAttendance(){if(!currentProfile)return;try{const r=await api('/admin/attendance',{method:'POST',body:JSON.stringify({studentId:currentProfile.student._id})});toast(r.message);const profile=await api(`/admin/students/${currentProfile.student._id}/profile`);showScannedProfile(profile,true);}catch(e){toast(e.message);}}
async function renderAttendance(f){const r=await api(`/admin/attendance?faculty=${f}`);$('content').innerHTML=card(`حضور اليوم — الفرقة ${f}`,`<div class="table-wrap"><table class="table"><thead><tr><th>الطالب</th><th>الكود</th><th>المجموعة</th><th>الوقت</th><th>الطريقة</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${esc(x.studentId?.name||'-')}</td><td>${esc(x.studentId?.code||'-')}</td><td>${x.studentId?.group||'-'}</td><td>${esc(x.time)}</td><td>${esc(x.method)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">لا توجد سجلات اليوم</td></tr>'}</tbody></table></div>`);}
async function renderEvaluation(f){
  const r=await api(`/evaluations?faculty=${f}`); activeEvaluation=r.activeSession;
  const setupBody='<div class="form-grid"><label>الشهر<select id="evalMonth">'+r.months.map(m=>'<option value="'+esc(m.month)+'">'+esc(m.month)+'</option>').join('')+'</select></label><label>التاريخ<input id="evalDate" type="date"></label><label>الدرجة النهائية<input id="evalMax" type="number" min="1" value="20"></label></div><button class="primary" onclick="startEvaluation()">بدء التقييم</button>'+(activeEvaluation?'<div class="session-banner">الجلسة الحالية: '+esc(activeEvaluation.month)+' — '+esc(activeEvaluation.date)+' — '+activeEvaluation.max+' درجة</div>':'');
  const inputBody='<div class="form-grid"><label>كود الطالب<input id="evalCode" maxlength="3"></label><label>الدرجة<input id="evalScore" type="number" min="0" step="0.5"></label></div><div class="actions"><button class="primary" onclick="saveEvaluation()">حفظ الدرجة</button><button class="ghost" onclick="startEvaluationScanner()">📷 فحص QR</button></div><div id="evalReader" class="scanner">كاميرا التقييم</div><div id="evalResult" class="result-box"></div>';
  const rows=r.rows.map(e=>'<tr><td>'+esc(e.studentId?.name||'-')+'</td><td>'+esc(e.code)+'</td><td>'+(e.studentId?.group||'-')+'</td><td>'+e.score+'/'+e.max+'</td><td>'+esc(e.month)+'</td><td>'+esc(e.date)+'</td></tr>').join('')||'<tr><td colspan="6" class="empty">لا توجد تقييمات</td></tr>';
  const table='<div class="table-wrap"><table class="table"><thead><tr><th>الطالب</th><th>الكود</th><th>المجموعة</th><th>الدرجة</th><th>الشهر</th><th>التاريخ</th></tr></thead><tbody>'+rows+'</tbody></table></div>';
  $('content').innerHTML=card('إعداد جلسة التقييم',setupBody)+card('إدخال الدرجة',inputBody)+card('التقييمات المسجلة',table);
}
async function startEvaluation(){try{const f=Number($('adminFaculty').value);const r=await api('/evaluations/sessions',{method:'POST',body:JSON.stringify({faculty:f,month:$('evalMonth').value,date:$('evalDate').value,max:Number($('evalMax').value)})});activeEvaluation=r.session;toast('بدأت جلسة التقييم');renderAdmin();}catch(e){toast(e.message);}}
async function saveEvaluation(){if(!activeEvaluation)return toast('ابدأ جلسة التقييم أولًا');try{const r=await api('/evaluations',{method:'POST',body:JSON.stringify({sessionId:activeEvaluation._id,code:$('evalCode').value,score:Number($('evalScore').value)})});$('evalResult').textContent=`تم حفظ ${r.evaluation.code}: ${r.evaluation.score}/${r.evaluation.max}`;toast(r.message);renderAdmin();}catch(e){toast(e.message);}}
function startEvaluationScanner(){if(!window.Html5Qrcode)return toast('مكتبة QR غير متاحة');stopScanner();scanner=new Html5Qrcode('evalReader');scanner.start({facingMode:'environment'},{fps:10,qrbox:220},txt=>{stopScanner();$('evalCode').value=String(txt).match(/(\d{3})$/)?.[1]||'';}).catch(()=>toast('تعذر تشغيل الكاميرا'));}
async function renderStudy(f){const r=await api(`/admin/settings?faculty=${f}`);$('content').innerHTML=card(`شهور الدراسة — الفرقة ${f}`,`<div class="form-grid"><label>الشهر<select id="monthName">${monthNames.map(m=>`<option>${m}</option>`).join('')}</select></label><label>عدد المحاضرات<input id="lectureCount" type="number" min="0"></label><label>تاريخ التقييم<input id="monthDate" type="date"></label></div><button class="primary" onclick="saveStudyMonth()">حفظ الشهر</button><div class="table-wrap" style="margin-top:18px"><table class="table"><thead><tr><th>الشهر</th><th>المحاضرات</th><th>تاريخ التقييم</th><th></th></tr></thead><tbody>${r.months.map(m=>`<tr><td>${esc(m.month)}</td><td>${m.lectures}</td><td>${esc(m.evaluationDate||'-')}</td><td><button class="mini danger-mini" onclick="deleteStudyMonth('${encodeURIComponent(m.month)}')">حذف</button></td></tr>`).join('')||'<tr><td colspan="4" class="empty">لا توجد شهور</td></tr>'}</tbody></table></div>`);}
async function saveStudyMonth(){try{const r=await api('/admin/study-months',{method:'POST',body:JSON.stringify({faculty:Number($('adminFaculty').value),month:$('monthName').value,lectures:Number($('lectureCount').value),evaluationDate:$('monthDate').value})});toast('تم حفظ الشهر');renderAdmin();}catch(e){toast(e.message);}}
async function deleteStudyMonth(m){try{await api(`/admin/study-months/${$('adminFaculty').value}/${m}` ,{method:'DELETE'});toast('تم حذف الشهر');renderAdmin();}catch(e){toast(e.message);}}
async function renderData(f){const r=await api(`/admin/settings?faculty=${f}`);if(!session.isMaster){$('content').innerHTML=card('البيانات',`<p>إعداد المجموعات والاستيراد متاحان لحساب Master فقط.</p>`);return;}const lists=r.lists||{};$('content').innerHTML=`${card('استيراد الطلاب من Excel',`<p class="muted">يدعم XLSX/XLS/CSV. الاستيراد يستبدل بيانات الفرقة المحددة.</p><input id="excelFile" type="file" accept=".xlsx,.xls,.csv"><button class="primary" style="margin-top:10px" onclick="importExcel()">رفع البيانات</button>`)}${card('إعداد المجموعة',`<div class="form-grid"><label>الفرقة<select id="gFaculty"><option value="3">3</option><option value="4">4</option></select></label><label>رقم المجموعة<select id="gNo">${Array.from({length:30},(_,i)=>`<option>${i+1}</option>`).join('')}</select></label><label>المكان<select id="gLocation">${(lists.locations||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>عضو هيئة التدريس<select id="gFacultyMember">${(lists.facultyMembers||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>الهيئة المعاونة<select id="gAssistant">${(lists.assistants||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>المشرف الخارجي<select id="gExternal">${(lists.externals||[]).map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><button class="primary" onclick="saveGroup()">حفظ المجموعة</button>`)}${card('المجموعات الحالية',`<div class="table-wrap"><table class="table"><thead><tr><th>الفرقة</th><th>المجموعة</th><th>المكان</th><th>هيئة التدريس</th><th>المعاون</th><th>المشرف الخارجي</th><th></th></tr></thead><tbody>${r.groups.map(g=>`<tr><td>${g.faculty}</td><td>${g.group}</td><td>${esc(g.location)}</td><td>${esc(g.facultyMember)}</td><td>${esc(g.assistant)}</td><td>${esc(g.external)}</td><td><button class="mini danger-mini" onclick="deleteGroup(${g.faculty},${g.group})">حذف</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">لا توجد مجموعات</td></tr>'}</tbody></table></div>`)} `;}
async function importExcel(){const file=$('excelFile').files?.[0];if(!file)return toast('اختر ملف Excel');const fd=new FormData();fd.append('file',file);fd.append('faculty',$('adminFaculty').value);try{const r=await api('/import/students',{method:'POST',body:fd});toast(r.message);renderAdmin();}catch(e){toast(e.message);}}
async function saveGroup(){try{const body={faculty:Number($('gFaculty').value),group:Number($('gNo').value),location:$('gLocation').value,facultyMember:$('gFacultyMember').value,assistant:$('gAssistant').value,external:$('gExternal').value};await api('/admin/groups',{method:'POST',body:JSON.stringify(body)});toast('تم حفظ المجموعة');renderAdmin();}catch(e){toast(e.message);}}
async function deleteGroup(f,g){if(!confirm('حذف إعداد المجموعة؟'))return;try{await api(`/admin/groups/${f}/${g}`,{method:'DELETE'});toast('تم الحذف');renderAdmin();}catch(e){toast(e.message);}}
async function renderReview(f){const r=await api(`/admin/settings?faculty=${f}`);const s=r.setting||{};const students=await api(`/admin/students?faculty=${f}`);const rows=[];for(const st of students.students){const p=await api(`/admin/students/${st._id}/profile`);rows.push(`<tr><td>${esc(st.name)}</td><td>${st.group||'-'}</td><td>${p.attendance.totalLectures}</td><td>${s.lectureGrade||0}</td><td>${p.summary.evaluationTotal}</td><td><b>${p.summary.total}</b></td></tr>`);} $('content').innerHTML=card(`مراجعة واعتماد — الفرقة ${f}`,`<p class="muted">المجموع الكلي = مجموع درجات التقييمات + (عدد المحاضرات × درجة المحاضرة).</p><div class="form-grid"><label>درجة المحاضرة<input id="lectureGrade" type="number" min="0" step="0.5" value="${s.lectureGrade||2}"></label></div><div class="actions"><button class="primary" onclick="saveLectureGrade()">حفظ درجة المحاضرة</button><button class="ghost" onclick="approveFaculty()">${s.approved?'إعادة اعتماد':'اعتماد النتائج'}</button></div><div class="table-wrap" style="margin-top:16px"><table class="table"><thead><tr><th>الطالب</th><th>المجموعة</th><th>المحاضرات</th><th>درجة المحاضرة</th><th>التقييمات</th><th>المجموع</th></tr></thead><tbody>${rows.join('')||'<tr><td colspan="6" class="empty">لا توجد بيانات</td></tr>'}</tbody></table></div>`);}
async function saveLectureGrade(){try{await api(`/admin/faculty/${$('adminFaculty').value}/lecture-grade`,{method:'POST',body:JSON.stringify({lectureGrade:Number($('lectureGrade').value)})});toast('تم الحفظ');renderAdmin();}catch(e){toast(e.message);}}
async function approveFaculty(){try{await api(`/admin/faculty/${$('adminFaculty').value}/approve`,{method:'POST'});toast('تم اعتماد النتائج');renderAdmin();}catch(e){toast(e.message);}}
function renderExport(){ $('content').innerHTML=card('تصدير النتائج',`<p class="muted">التصدير متاح بعد اعتماد النتائج.</p><div class="actions"><button class="primary" onclick="downloadExport(3)">تصدير الفرقة الثالثة XLSX</button><button class="primary" onclick="downloadExport(4)">تصدير الفرقة الرابعة XLSX</button></div>`);}
async function downloadExport(f){try{const token=localStorage.getItem('tadreebi_token');const response=await fetch(`${API_BASE}/export/faculty/${f}/xlsx`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){const x=await response.json();throw new Error(x.message||'فشل التصدير');}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`tadreebi-faculty-${f}.xlsx`;a.click();URL.revokeObjectURL(url);}catch(e){toast(e.message);}}
async function renderSettings(){ $('content').innerHTML=card('إعدادات الحساب',`<p>تسجيل الدخول الحالي: <b>${esc(session.name)}</b></p><button class="ghost" onclick="logout()">تسجيل الخروج</button><p class="muted" style="margin-top:15px">يمكن تغيير API URL من LocalStorage باستخدام المفتاح <code>tadreebi_api_url</code>.</p>`);}
async function renderPermissions(){if(!session.isMaster)return;const r=await api('/admin/permissions');$('content').innerHTML=card('صلاحيات الحسابات الإدارية',`${r.admins.map(a=>`<div class="perm-card"><h4>${esc(a.admin.name)} — ${esc(a.admin.email)}</h4><div class="form-grid">${[3,4].map(f=>{const p=a.permissions.find(x=>x.faculty===f)||{groups:[],allowAll:false};return `<label>الفرقة ${f}<input data-perm-admin="${a.admin.id}" data-perm-faculty="${f}" value="${(p.groups||[]).join(',')}" placeholder="1,6,11,21"></label>`;}).join('')}</div><button class="primary" onclick="savePermissions('${a.admin.id}')">حفظ الصلاحيات</button></div>`).join('')||'<p class="empty">لا توجد حسابات</p>'}`);}
async function savePermissions(id){const permissions=[3,4].map(f=>({faculty:f,groups:(document.querySelector(`[data-perm-admin="${id}"][data-perm-faculty="${f}"]`).value||'').split(',').map(x=>Number(x.trim())).filter(x=>x>=1&&x<=30)}));try{await api(`/admin/permissions/${id}`,{method:'PUT',body:JSON.stringify({permissions})});toast('تم حفظ الصلاحيات');}catch(e){toast(e.message);}}
window.addEventListener('DOMContentLoaded',init);
